### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by vsly-ar** [mix1009/ffcache#1]
First of all, thanks for the good plugin!

Any plans for adding web support? 
Seems possible with local storage.

**Comment by mix1009** [comment]
Thank you for the interest and suggestion.

Do you mean localstorage package?

**Comment by vsly-ar** [comment]
> Thank you for the interest and suggestion.
> 
> Do you mean localstorage package?

I've meant HTML5 Web Storage API (`window.localStorage`), regardless of exact dart implementation.

**Comment by mix1009** [comment]
I've implemented web support on web_support branch.
It will be merged into main branch after more testing.

It uses idb_shim package for web storage api. It's simpler than using indexed_db directly.
It also seems to support more browsers.

**Comment by vsly-ar** [comment]
> I've implemented web support on web_support branch.
> It will be merged into main branch after more testing.

Here's a small test app for this purpose: https://github.com/vsly-ru/ffcache_web_test
Currently build fails both on iOS and Web with following errors:
``` python
Launching lib/main.dart on Chrome in debug mode...
../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart:102:41: 
Error: The argument type 'Object' can't be assigned to the parameter type 'String'.
 - 'Object' is from 'dart:core'.
            if (remainingDurationForKey(key).isNegative) {
                                        ^
../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart:114:39: 
Error: The getter 'filename' isn't defined for the class 'FFCache'.
 - 'FFCache' is from 'package:ffcache/ffcache.dart'
 ('../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'filename'.
              final val = _timeoutMap[filename];
                                      ^^^^^^^^
../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart:116:32: 
Error: The getter 'filename' isn't defined for the class 'FFCache'.
 - 'FFCache' is from 'package:ffcache/ffcache.dart'
 ('../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'filename'.
                _newTimeoutMap[filename] = val;
                               ^^^^^^^^
../../flutter/.pub-cache/git/ffcache-18df5f859cadcc60c144aab3a5f70aaa06c1affb/lib/ffcache.dart:481:19: 
Warning: Operand of null-aware operation '!' has type 'IdbFactory' which excludes null.
 - 'IdbFactory' is from 'package:idb_shim/idb.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/idb_shim-2.0.1/lib/idb.dart').
      _db = await idbFactory!.open("${_basePath}.db", version: 1,
                  ^
Failed to compile application.
```

**Comment by mix1009** [comment]
Thank you for the feedback. I made some fixes.

I had run below commands to get latest ffcache from your example app.
flutter packages upgrade
flutter packages get

You should call init():
      await _cache.init(); 

web version does have some problem without calling init() manually.
I think there is some delay initializing the localStorage.

**Comment by vsly-ar** [comment]
@mix1009 great! I've upgraded packages and added `init()` to the code above (along with more tests) and almost everything seems to work fine so far. Except `getBytes` returning `List<dynamic>` instead of `List<int>` thus throwing an exception.

**Comment by mix1009** [comment]
Thanks again. I've fixed the getBytes bug. It should now work :)

**Comment by vsly-ar** [comment]
<img width="200" alt="iPhone 12 mini 2021-10-23 21-52-14" src="https://user-images.githubusercontent.com/39321074/138561328-8f642726-4555-4672-b1d7-c6c7c93553c4.png"><img width="220" alt="Flutter Demo 2021-10-23 21-54-31" src="https://user-images.githubusercontent.com/39321074/138561397-06314c44-bad1-4ee1-b4c3-89fcd656fef3.png"><img width="200" alt="Android Emulator - Pixel_2_API_29:5554 2021-10-23 22-04-10" src="https://user-images.githubusercontent.com/39321074/138561703-f46b8464-f026-4c8d-b67f-4ae8518e0312.png">

Perfect, looks like all the essential functions are operational and the Web support is ready!
Thanks for the new feature 👍
